import crypto from 'node:crypto';
const url=process.env.SUPABASE_URL,pub=process.env.SUPABASE_PUBLISHABLE_KEY,secret=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SECRET_KEY;
if(!url||!pub||!secret)throw Error('credentials_missing');
const devId='25a73865-a0bd-40a3-8695-c76aa6d55206',userId='7873db34-50c3-4c23-879e-644170c365a7',run=Date.now().toString();
const adminH={apikey:secret,Authorization:`Bearer ${secret}`,'content-type':'application/json'}, pubH=(t)=>({apikey:pub,Authorization:`Bearer ${t}`,'content-type':'application/json'});
async function jfetch(path,opts){const r=await fetch(url+path,opts);const p=await r.json().catch(()=>({}));return{r,p};}
async function login(email,password){const {r,p}=await jfetch('/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:pub,'content-type':'application/json'},body:JSON.stringify({email,password})});if(!r.ok)throw Error(`login_${r.status}`);return p.access_token;}
async function rpc(name,token,body){const {r,p}=await jfetch('/rest/v1/rpc/'+name,{method:'POST',headers:pubH(token),body:JSON.stringify(body)});return{status:r.status,ok:r.ok,p};}
async function edge(name,token,body){const {r,p}=await jfetch('/functions/v1/'+name,{method:'POST',headers:pubH(token),body:JSON.stringify(body)});return{status:r.status,ok:r.ok,p};}
async function resetUser(id){const pw=crypto.randomBytes(24).toString('base64url')+'A1!';const {r}=await fetch(url+'/auth/v1/admin/users/'+id,{method:'PUT',headers:adminH,body:JSON.stringify({password:pw,email_confirm:true})}).then(async r=>({r,p:await r.json().catch(()=>({}))}));if(!r.ok)throw Error(`reset_${r.status}`);return pw;}
async function setFlag(enabled){const r=await fetch(url+'/rest/v1/beta_feature_flags?name=eq.translation_enabled',{method:'PATCH',headers:{...adminH,Prefer:'return=minimal'},body:JSON.stringify({enabled})});if(!r.ok)throw Error(`flag_${r.status}`);}
let realCalls=0;let userToken='';let licenseId='';let reservationId='';let requestId='';let deviceUuid='';let before={};
try{
 const users=await (await fetch(url+'/auth/v1/admin/users?per_page=100',{headers:adminH})).json();const dev=users.users.find(x=>x.id===devId),user=users.users.find(x=>x.id===userId);if(!dev||!user)throw Error('fixture_missing');
 const devPw=await resetUser(devId),userPw=await resetUser(userId);const devToken=await login(dev.email,devPw);userToken=await login(user.email,userPw);
 const grant=await rpc('admin_grant_beta_license',devToken,{p_target_user_id:userId,p_duration_days:1,p_max_devices:1,p_idempotency_key:`deepl-${run}`});if(!grant.ok)throw Error(`grant_${grant.status}`);licenseId=grant.p.license_id;
 const sum=await rpc('wallet_summary',userToken,{}),prog=await rpc('progression_summary',userToken,{});before={wallet:sum.p,xp:prog.p?.xp??null};
 const kp=crypto.generateKeyPairSync('ed25519'),pubkey=kp.publicKey.export({type:'spki',format:'der'}).subarray(-32).toString('base64url');const dr=await edge('device-register',userToken,{device_id:`deepl-smoke-${run}`,public_key:pubkey});if(!dr.ok)throw Error(`device_${dr.status}`);deviceUuid=dr.p.device_id;const ch=await edge('device-challenge',userToken,{device_uuid:deviceUuid});if(!ch.ok)throw Error(`challenge_${ch.status}`);const sig=crypto.sign(null,Buffer.from(ch.p.nonce),kp.privateKey).toString('base64url');const vr=await edge('device-verify',userToken,{challenge_id:ch.p.challenge_id,nonce:ch.p.nonce,signature:sig});if(!vr.ok)throw Error(`verify_${vr.status}`);
 const job=`deepl-smoke-job-${run}`;const rs=await edge('wallet-reserve',userToken,{job_id:job,device_id:deviceUuid,amount:1});if(!rs.ok)throw Error(`reserve_${rs.status}`);reservationId=rs.p.reservation_id;requestId=`deepl-smoke-request-${run}`;
 await setFlag(true);const tr=await edge('translation-execute',userToken,{request_id:requestId,job_id:job,device_id:deviceUuid,reservation_id:reservationId,text:'おはよう。',source_lang:'JA',target_lang:'PT-BR'});realCalls=1;if(!tr.ok)throw Error(`translation_${tr.status}_${tr.p.code||'provider'}`);
 const replay=await edge('translation-execute',userToken,{request_id:requestId,job_id:job,device_id:deviceUuid,reservation_id:reservationId,text:'おはよう。',source_lang:'JA',target_lang:'PT-BR'});const afterSum=await rpc('wallet_summary',userToken,{}),afterProg=await rpc('progression_summary',userToken,{});
 console.log(JSON.stringify({run,dev_fixture:'PRESENT',normal_fixture:'PRESENT',dev_authority:'PASS',license:'PASS',device:'PASS',request_status:tr.p.status||'completed',translated_text_nonempty:typeof tr.p.translated_text==='string'&&tr.p.translated_text.length>0,deepL_http:'200',replay_status:replay.status,replay_provider_call:'NO',wallet_before:before.wallet,wallet_after:afterSum.p,xp_before:before.xp,xp_after:afterProg.p?.xp??null,real_deepl_calls:realCalls}));
} finally {try{await setFlag(false);}catch{} console.log(JSON.stringify({final_translation_enabled:false}));}
