create or replace function public.claim_daily_yk() returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare u uuid:=auth.uid(); d date:=current_date; p integer; a integer;
begin if u is null then raise exception 'unauthorized'; end if; if exists(select 1 from public.yk_daily_claims where user_id=u and claim_day=d) then return jsonb_build_object('amount',0,'already_claimed',true); end if; select coalesce(sum(amount),0) into p from public.yk_ledger where user_id=u and bucket='permanent'; a:=greatest(0,5-p); insert into public.yk_daily_claims(user_id,claim_day,amount) values(u,d,a); if a>0 then insert into public.yk_ledger(user_id,amount,bucket,event_type,reference_id,expires_at) values(u,a,'daily','daily_claim',d::text,d+1); end if; return jsonb_build_object('amount',a,'already_claimed',false,'claim_day',d); end $$;
create or replace function public.wallet_summary() returns jsonb language sql security definer set search_path=pg_catalog,public as $$ select jsonb_build_object('daily',coalesce((select sum(amount) from public.yk_ledger where user_id=auth.uid() and bucket='daily' and (expires_at is null or expires_at>now())),0),'subscription',coalesce((select sum(amount) from public.yk_ledger where user_id=auth.uid() and bucket='subscription'),0),'permanent',coalesce((select sum(amount) from public.yk_ledger where user_id=auth.uid() and bucket='permanent'),0),'reserved',coalesce((select sum(amount) from public.yk_reservations where user_id=auth.uid() and status='reserved'),0)); $$;
create or replace function public.reserve_translation_yk(p_job_id text,p_device_id uuid,p_amount integer default 1) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare u uuid:=auth.uid(); l uuid; available integer; rid uuid;
begin if u is null then raise exception 'unauthorized'; end if; if nullif(trim(p_job_id),'') is null or p_amount<1 then raise exception 'invalid_reservation'; end if; select id into l from public.licenses where user_id=u and status='active' and (expires_at is null or expires_at>now()) order by expires_at desc nulls last limit 1; if l is null then raise exception 'license_not_found'; end if; if not exists(select 1 from public.license_devices where id=p_device_id and user_id=u and license_id=l and status='active') then raise exception 'device_not_found'; end if; select id into rid from public.yk_reservations where user_id=u and job_id=trim(p_job_id); if rid is not null then return jsonb_build_object('reservation_id',rid,'already_reserved',true); end if; select coalesce(sum(amount),0)-coalesce((select sum(amount) from public.yk_reservations where user_id=u and status='reserved'),0) into available from public.yk_ledger where user_id=u and (expires_at is null or expires_at>now()); if available<p_amount then raise exception 'insufficient_yk'; end if; insert into public.yk_reservations(user_id,job_id,amount,status) values(u,trim(p_job_id),p_amount,'reserved') returning id into rid; return jsonb_build_object('reservation_id',rid,'amount',p_amount,'status','reserved'); end $$;
create or replace function public.finalize_yk_reservation(p_reservation_id uuid,p_release boolean default false) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare u uuid:=auth.uid(); s text; a integer; j text;
begin if u is null then raise exception 'unauthorized'; end if; select status,amount,job_id into s,a,j from public.yk_reservations where id=p_reservation_id and user_id=u for update; if s is null then raise exception 'reservation_not_found'; end if; if s<>'reserved' then return jsonb_build_object('reservation_id',p_reservation_id,'status',s,'idempotent',true); end if; update public.yk_reservations set status=case when p_release then 'released' else 'consumed' end,updated_at=now() where id=p_reservation_id; if not p_release then insert into public.yk_ledger(user_id,amount,bucket,event_type,reference_id) values(u,-a,'daily','translation_debit',j); end if; return jsonb_build_object('reservation_id',p_reservation_id,'status',case when p_release then 'released' else 'consumed' end); end $$;
create or replace function public.award_translation_xp(p_reference_id text,p_amount integer default 10) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$ declare u uuid:=auth.uid(); n integer; begin if u is null then raise exception 'unauthorized'; end if; if p_amount<1 or nullif(trim(p_reference_id),'') is null then raise exception 'invalid_progression_event'; end if; insert into public.progression_ledger(user_id,amount,event_type,reference_id) values(u,p_amount,'translation',trim(p_reference_id)) on conflict do nothing; get diagnostics n=row_count; return jsonb_build_object('credited',n=1,'amount',case when n=1 then p_amount else 0 end); end $$;
create or replace function public.progression_summary() returns jsonb language sql security definer set search_path=pg_catalog,public as $$ with x as (select coalesce(sum(amount),0) xp from public.progression_ledger where user_id=auth.uid()), r as (select name from public.progression_ranks,x where threshold<=x.xp order by threshold desc limit 1) select jsonb_build_object('xp',(select xp from x),'rank',coalesce((select name from r),'Leitor Iniciante')); $$;
revoke all on function public.claim_daily_yk(),public.wallet_summary(),public.reserve_translation_yk(text,uuid,integer),public.finalize_yk_reservation(uuid,boolean),public.award_translation_xp(text,integer),public.progression_summary() from public,anon;
grant execute on function public.claim_daily_yk(),public.wallet_summary(),public.reserve_translation_yk(text,uuid,integer),public.finalize_yk_reservation(uuid,boolean),public.award_translation_xp(text,integer),public.progression_summary() to authenticated;
